/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasAkhir;

import Koneksi.connect;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author toshiba
 */
public class Penjualan extends javax.swing.JFrame {

    /**
     * Creates new form Penjualan
     */
    connect db;
    public ArrayList barcode = new ArrayList();
    public ArrayList tanggal = new ArrayList();
    public ArrayList nama = new ArrayList();
    public ArrayList satuan = new ArrayList();
    public ArrayList harga = new ArrayList();
    public ArrayList stok = new ArrayList();
    public ArrayList diskon = new ArrayList();
    public ArrayList total = new ArrayList();
    int h;
    int r;
    
    
    public Penjualan() {
        db = new connect();
        initComponents();
        setHeader();
        new Thread(){
            public void run(){
            while (true) {            
            Calendar kal = new GregorianCalendar();
            int tahun = kal.get(Calendar.YEAR);
            int bulan = kal.get(Calendar.MONTH)+1;
            int hari = kal.get(Calendar.DAY_OF_MONTH);
            int jam = kal.get(Calendar.HOUR_OF_DAY);
            int menit = kal.get(Calendar.MINUTE);
            int detik = kal.get(Calendar.SECOND);
            
            String tanggal = hari+"/"+bulan+"/"+tahun;
            String waktu = jam+":"+menit+":"+detik;
            
            txttanggal.setText(tanggal);
            txtjam.setText(waktu);
            }
        }
        }.start();
    }
    public void setHeader(){
        tblKasir.setOpaque(false);
        ((DefaultTableCellRenderer) tblKasir.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        JTableHeader header = tblKasir.getTableHeader();
        header.setPreferredSize(new Dimension(20,50));
        header.setOpaque(false);
        header.setBackground(Color.WHITE);
        header.setFont(new Font("Courier new", Font.BOLD,18));
    }
            

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setTable(){
        int t = 0;
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("Kode Barang");
        tbl.addColumn("Tanggal");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Satuan");
        tbl.addColumn("Harga");
        tbl.addColumn("Stok");
        tbl.addColumn("Diskon");
        tbl.addColumn("Total");
        for (int n=0; n<barcode.size(); n++){
            t += Integer.parseInt(total.get(n).toString());
            tbl.addRow(new Object[]{
                barcode.get(n),
                tanggal.get(n),
                nama.get(n), 
                satuan.get(n),
                harga.get(n),
                stok.get(n),
                diskon.get(n),
                total.get(n)
            });
        }
        int d = t/100000*5000;
        txttotal.setText(Integer.toString(t));
        txtdiskon.setText(Integer.toString(d));
        tblKasir.setModel(tbl);
        if (tblKasir.getColumnModel().getColumnCount() > 0) {
            tblKasir.getColumnModel().getColumn(0).setResizable(false);
            tblKasir.getColumnModel().getColumn(0).setPreferredWidth(160);
            tblKasir.getColumnModel().getColumn(1).setResizable(false);
            tblKasir.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblKasir.getColumnModel().getColumn(2).setResizable(false);
            tblKasir.getColumnModel().getColumn(2).setPreferredWidth(315);
            tblKasir.getColumnModel().getColumn(3).setResizable(false);
            tblKasir.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblKasir.getColumnModel().getColumn(4).setResizable(false);
            tblKasir.getColumnModel().getColumn(4).setPreferredWidth(170);
            tblKasir.getColumnModel().getColumn(5).setResizable(false);
            tblKasir.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblKasir.getColumnModel().getColumn(6).setResizable(false);
            tblKasir.getColumnModel().getColumn(6).setPreferredWidth(110);
            tblKasir.getColumnModel().getColumn(7).setResizable(false);
            tblKasir.getColumnModel().getColumn(7).setPreferredWidth(150);
        }
    }
    public void addKasir(){
        try {
            ResultSet rs;
            rs = db.searchDB(txtsearch.getText());
            while(rs.next()){
                    barcode.add(rs.getString("Barcode"));
                    tanggal.add(txtjam.getText());
                    nama.add(rs.getString("Nama"));
                    satuan.add(txtsatuan.getValue());
                    harga.add(rs.getInt("Harga"));
                    stok.add(rs.getInt("Stok"));
                    diskon.add("-");
                    total.add(rs.getInt("harga")*txtsatuan.getValue());
                System.out.println("penambahan berhasil");       
            }
        } catch (SQLException ex) {
            System.out.println("tidak menemukan"+ex);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtsisa = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txttotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtjam = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtsatuan = new com.toedter.components.JSpinField();
        txtsearch = new javax.swing.JTextField();
        txttanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKasir = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1350, 500));
        setPreferredSize(new java.awt.Dimension(1350, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 100, 40));

        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 100, 40));

        jButton1.setBackground(new java.awt.Color(58, 4, 58));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADMIN");
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 610, 110, 40));

        txtsisa.setBackground(new java.awt.Color(255, 255, 255));
        txtsisa.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtsisa.setForeground(new java.awt.Color(255, 255, 255));
        txtsisa.setText("0");
        getContentPane().add(txtsisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 620, 150, 30));

        txtdiskon.setBackground(new java.awt.Color(255, 255, 255));
        txtdiskon.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtdiskon.setForeground(new java.awt.Color(255, 255, 255));
        txtdiskon.setText("0");
        getContentPane().add(txtdiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 530, 150, 30));

        txtbayar.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtbayar.setForeground(new java.awt.Color(255, 255, 255));
        txtbayar.setOpaque(false);
        getContentPane().add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 570, 150, 30));

        txttotal.setBackground(new java.awt.Color(255, 255, 255));
        txttotal.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txttotal.setForeground(new java.awt.Color(255, 255, 255));
        txttotal.setText("0");
        getContentPane().add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 490, 150, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOTAL   : Rp.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 490, 150, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Diskon  : Rp.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 150, 30));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BAYAR   : Rp.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 150, 30));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SISA    : Rp.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, 150, 30));
        jLabel5.getAccessibleContext().setAccessibleName("Kembalian :");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 350, 3));

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jam      :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 120, 30));

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal  :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 30));

        txtjam.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtjam.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 140, 30));

        jButton7.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Simpan");
        jButton7.setContentAreaFilled(false);
        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, 40));

        jButton6.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Tambah");
        jButton6.setContentAreaFilled(false);
        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 80, 40));

        jButton5.setBackground(new java.awt.Color(0, 0, 204));
        jButton5.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("BAYAR");
        jButton5.setContentAreaFilled(false);
        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 570, -1, 30));

        txtsatuan.setOpaque(false);
        getContentPane().add(txtsatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 80, 40));

        txtsearch.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(255, 255, 255));
        txtsearch.setOpaque(false);
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 230, 40));

        txttanggal.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        txttanggal.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, 30));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setOpaque(false);

        tblKasir.setAutoCreateRowSorter(true);
        tblKasir.setBackground(new java.awt.Color(24, 0, 47));
        tblKasir.setForeground(new java.awt.Color(255, 255, 255));
        tblKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kodebarang", "Tanggal", "NamaBarang", "Satuan", "Harga", "Stok", "Diskon", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKasir.setToolTipText("");
        tblKasir.setAlignmentX(0.0F);
        tblKasir.setAlignmentY(0.0F);
        tblKasir.setColumnSelectionAllowed(true);
        tblKasir.setDragEnabled(true);
        tblKasir.setEditingColumn(1);
        tblKasir.setGridColor(new java.awt.Color(255, 255, 255));
        tblKasir.setOpaque(false);
        tblKasir.setPreferredSize(new java.awt.Dimension(1235, 510));
        tblKasir.setRowHeight(30);
        tblKasir.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tblKasir.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblKasir.setShowGrid(false);
        tblKasir.setSurrendersFocusOnKeystroke(true);
        tblKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKasirMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKasir);
        tblKasir.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tblKasir.getColumnModel().getColumnCount() > 0) {
            tblKasir.getColumnModel().getColumn(0).setResizable(false);
            tblKasir.getColumnModel().getColumn(0).setPreferredWidth(160);
            tblKasir.getColumnModel().getColumn(1).setResizable(false);
            tblKasir.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblKasir.getColumnModel().getColumn(2).setResizable(false);
            tblKasir.getColumnModel().getColumn(2).setPreferredWidth(315);
            tblKasir.getColumnModel().getColumn(3).setResizable(false);
            tblKasir.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblKasir.getColumnModel().getColumn(4).setResizable(false);
            tblKasir.getColumnModel().getColumn(4).setPreferredWidth(170);
            tblKasir.getColumnModel().getColumn(5).setResizable(false);
            tblKasir.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblKasir.getColumnModel().getColumn(6).setResizable(false);
            tblKasir.getColumnModel().getColumn(6).setPreferredWidth(110);
            tblKasir.getColumnModel().getColumn(7).setResizable(false);
            tblKasir.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 107, 1250, 300));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/n1.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jLabel1.setMinimumSize(new java.awt.Dimension(960, 680));
        jLabel1.setPreferredSize(new java.awt.Dimension(1350, 900));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1350, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        barcode.clear();
        tanggal.clear();
        nama.clear(); 
        satuan.clear();
        harga.clear();
        stok.clear();
        diskon.clear();
        total.clear();
        txtbayar.setText("");
        txtsisa.setText("0");
        setTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int t = Integer.parseInt(txttotal.getText());
        int d = Integer.parseInt(txtdiskon.getText());
        int b = Integer.parseInt(txtbayar.getText());
        int s = b-t-d;
        txtsisa.setText(Integer.toString(s));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(txtsearch.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Masukan Barcode atau Nama Barang");
        }
        else{
            addKasir();
        setTable();
        txtsearch.setText("");
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = tblKasir.getSelectedRow();
        barcode.remove(row);
        tanggal.remove(row);
        nama.remove(row); 
        satuan.remove(row);
        harga.remove(row);
        stok.remove(row);
        diskon.remove(row);
        total.remove(row);
        setTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKasirMouseClicked
        r = tblKasir.getSelectedRow();
        txtsatuan.setValue((int) satuan.get(r));
    }//GEN-LAST:event_tblKasirMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int t = txtsatuan.getValue() * (int) harga.get(r);
        Object set = total.set(r,t);
        Object set1 = satuan.set(r, txtsatuan.getValue());
        setTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTable tblKasir;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JLabel txtdiskon;
    private javax.swing.JLabel txtjam;
    private com.toedter.components.JSpinField txtsatuan;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JLabel txtsisa;
    private javax.swing.JLabel txttanggal;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
